server:
  port: 8012

spring:
  application:
    name: cloud-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password2019
    url: jdbc:mysql://39.97.255.173:3306/cloud_xr?useUnicode=true&characterEncoding=utf8