server:
  port: 2006
spring:
  application:
    name: dynamic-data-service
  datasource:
    dynamic:
      primary: master
      datasource:
        master: # 默认为主库
          url: jdbc:mysql://39.107.246.93:3306/seata_order
          username: root
          password: Password_2019
          driver-class-name: com.mysql.jdbc.Driver
        slave2:
          username: root
          password: Password_2019
          driverclassname: com.mysql.jdbc.Driver
          url: jdbc:mysql://39.107.246.93:3306/seata_storage?characterEncoding=utf8&useSSL=false
        slave3:
          username: root
          password: Password_2019
          driverclassname: com.mysql.jdbc.Driver
          url: jdbc:mysql://39.107.246.93:3306/seata_account?characterEncoding=utf8&useSSL=false

mybatis:
  mapperLocations: classpath:mapper/*.xml

## 分布式事务组件Seata 配置项
seata:
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: dynamic-data-service-fescar-service-group # Seata 事务组编号，用于 TC 集群名
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    vgroupMapping:
      dynamic-data-service-fescar-service-group: default
      #（注：tx-service-group值要与该项名称一致）
    grouplist:
      default: localhost:8091