server:
  port: 8012

spring:
  application:
    name: cloud-order-service
  rabbitmq:
    host: 39.107.246.93
    port: 5672
    username: guest
    password: guest
    #listener:
     # simple:
      #  acknowledge-mode: auto
      #acknowledge-mode: acknowledge-mo #manual