server:
  port: 2001

spring:
  application:
    name: seata-order-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.246.93:3306/seata_order
    username: root
    password: Password_2019

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

## 分布式事务组件Seata 配置项
seata:
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: tx-service-seata # Seata 事务组编号，用于 TC 集群名
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    vgroup-mapping:
      tx-service-seata: default
      #（注：tx-service-group值要与该项名称一致）
    grouplist:
      efault: 127.0.0.1:8091