server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.246.93:3306/seata_order
    username: root
    password: Password_2019

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

#seata 配置， 代替file.conf和registry.conf配置
seata:
  enabled: true
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  tx-service-group: sfs_mis_tx_group
  client:
    rm-report-success-enable: true
    # 异步提交缓存队列长度（默认10000）
    rm-async-commit-buffer-limit: 1000
    # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-commit-retry-count:   3
    # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3
    support:
      # 数据源自动代理开关（默认false关闭）
      spring-datasource-autoproxy: true
  service:
    vgroup-mapping:
      # TC 集群（必须与seata-server保持一致）
      sfs_mis_tx_group: seata
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace:
      userName: "nacos"
      password: "nacos"